<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0-windows7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<BaseOutputPath>..\bin</BaseOutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NLog" Version="6.0.7" />
	</ItemGroup>
	<PropertyGroup>
		<SharedConfigDir>$(SolutionDir)\OpenDwg\Shared</SharedConfigDir>
	</PropertyGroup>
	<Target Name="CopyNLogConfig" AfterTargets="Build">
		<Copy
		  SourceFiles="$(SharedConfigDir)\NLog.$(Configuration).config"
		  DestinationFiles="$(OutDir)NLog.config"
		  SkipUnchangedFiles="true"
		  Condition="Exists('$(SharedConfigDir)\NLog.$(Configuration).config')" />
	</Target>



</Project>
